[project]
name = "cve-2025-59501"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msal>=1.34.0",
    "requests>=2.32.5",
    "urllib3>=2.5.0",
]
