services:
  mongodb:
    image: mongo:7.0.5
    container_name: cve-2025-14847-lab
    ports:
      - "27017:27017"
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    command: ["mongod", "--bind_ip_all", "--networkMessageCompressors", "zlib"]
    restart: always