version: '2'
services:
   phpcollab:
     ports:
       - "8088:80"
     image: jlkinsel/exploit-cve-2017-6090
   mysql:
     ports:
       - "3306:3306"
     image: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: changeme
       MYSQL_DATABASE: phpcollab
       MYSQL_USER: phpcollab
       MYSQL_PASSWORD: changeme

